{% set name = "cppyy-cling" %}
{% set version = "6.25.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy-cling/cppyy-cling-{{ version }}.tar.gz
  sha256: bedb63a5b47a2bcb482f793fbd992f4b4a9318dd0dbd24e6dd57de07c30b66fd
  patches:
    - use-dumb-setup.py.patch
    - llvm.patch
    # Disable use of llvm-config, a binary which we cannot invoke when cross-compiling
    - cross.patch  # [build_platform != target_platform]
    # Use pre-built generated files when we cannot invoke rootcling
    - rootcling.patch  # [build_platform != target_platform]
    - clang-cpp.patch
    - pri.patch
    - thread.patch

build:
  number: 1
  # cross-python does not support pypy yet
  skip: true  # [build_platform != target_platform and python_impl == "pypy"]

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - sed
    - cmake
  host:
    - python
    - pip
    - zlib
    - clangdev =9.0.1 root_62400*
    - llvmdev 9
    - llvm 9
  run:
    - {{ compiler('cxx') }}
    - python

test:
  commands:
    - which rootcling                                                           # [unix]
    # calling rootcling directly without argument fails but it should find all
    # its libraries (it exits with 134 on macOS otherwise.)
    - bash -c "${SP_DIR}"'/cppyy_backend/bin/rootcling; [[ $? == 1 ]]'          # [unix]
    - which cppyy-generator                                                     # [unix]
    - cling-config --incdir
    - which genreflex                                                           # [unix]

about:
  home: https://pypi.org/project/cppyy-cling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A repackaging of Cling for Automatic Python-C++ Bindings
  description: |
    A repackaging of Cling, the interactive C++ interpreter, including C/C++
    wrappers that expose no further external headers or types.
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy-backend/src/master/cling/

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
