context:
  version: "6.32.8"

package:
  name: cppyy-cling
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cppyy-cling/cppyy_cling-${{ version }}.tar.gz
  sha256: f51ea2e9bd1418c27d1fca3ba97e322ad660a5e18180aad2d17fb55db43a0b49
  patches:
    - 0001-Simplify-setup.py.patch
    # Disable use of llvm-config, a binary which we cannot install since it pulls in libllvm which breaks the build (also, we cannot use it when cross-compiling)
    - 0002-Do-not-use-llvm-config-when-cross-compiling.patch
    # Use pre-built generated files when we cannot invoke rootcling
    - 0003-use-pre-built-dictionary-and-rootmap.patch
    - 0004-link-against-libclangASTMatchers.patch
    - 0005-make-sure-C-formatting-symbols-are-available-in-C.patch
    - 0006-add-ThreadLocalStorage.h-directory.patch
    # Revert patch for non-macOS https://github.com/conda-forge/cppyy-cling-feedstock/pull/40#issuecomment-975781900
    - 0007-.patch  # [osx]
    # Do not use -march=native on platforms that do not support it yet.
    - 0008-clang-for-aarch64-does-not-support-march-native.patch
    # Fix dependency resolution when building rootcling
    - 0009-Fix-order-of-clang-libraries.patch
    # Fix https://github.com/conda-forge/cppyy-cling-feedstock/pull/56#issuecomment-1800307065
    - 0010-Remove-libLLVM.so-when-linking.patch
    - 0011-Hardcode-C-include-path-from-host.patch

build:
  number: 0
  skip:
    - win
  python:
    entry_points:
      - cling-config = cppyy_backend._cling_config:main
      - genreflex = cppyy_backend._genreflex:main
      - rootcling = cppyy_backend._rootcling:main
      - cppyy-generator = cppyy_backend._cppyy_generator:main

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - sed
    - cmake
    # We need a find that understand -name
    - findutils
    - if: unix
      then: make
  host:
    - libboost-headers
    - python
    - pip
    - setuptools
    - zlib
    - clangdev =13 root_63004*
    # Same pin as clangdev
    - if: osx
      then: libcxx-devel ==${{ cxx_compiler_version }}
  run:
    # We need a C++ compiler at runtime to compile cppdef snippets and glue
    # code and also so that all the standard headers are available. We do not
    # need the exact compiler that was used during the build {{ compiler('cxx') }}
    # but just any functional C++ compiler.
    - cxx-compiler
    - python
    - if: osx
      then: libcxx-devel ==${{ cxx_compiler_version }}

tests:
  - files:
      recipe:
        - test.h
    script:
      - rootcling -h
      - rootcling test.dict test.h
      - genreflex -h

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A repackaging of Cling for Automatic Python-C++ Bindings
  description: |
    A repackaging of Cling, the interactive C++ interpreter, including C/C++
    wrappers that expose no further external headers or types.
  homepage: https://pypi.org/project/cppyy-cling
  repository: https://bitbucket.org/wlav/cppyy-backend/src/master/cling/
  documentation: http://cppyy.readthedocs.io/

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
